# Generated by Django 4.1.4 on 2022-12-31 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCsvModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=100, verbose_name='画像名')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
            ],
            options={
                'verbose_name': 'image',
            },
        ),
    ]
