# Generated by Django 4.1.4 on 2023-01-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageLinkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=100, verbose_name='画像名')),
                ('link', models.CharField(max_length=100, verbose_name='リンク')),
            ],
            options={
                'verbose_name': 'link',
            },
        ),
    ]
