# Generated by Django 4.1.4 on 2023-01-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_imagelinkmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelinkmodel',
            name='image_name',
            field=models.CharField(max_length=1000, verbose_name='画像名'),
        ),
        migrations.AlterField(
            model_name='imagelinkmodel',
            name='link',
            field=models.CharField(max_length=1000, verbose_name='リンク'),
        ),
    ]
